"""Top-level public surface for ``mh-gateway``."""

from mh_gateway.adapters import (
    AuthorizationProvider,
    ConfigProvider,
    EvalResultRepository,
    LLMProviderService,
    LLMResolveSpec,
    M2MAuthenticator,
    MetadataRepository,
    OutboundAuthProvider,
    OutboundRequestContext,
    SessionRepository,
    UserAuthenticator,
    UserIdentity,
    has_broad_permission,
    match_permission,
)
from mh_gateway.app import (
    AdapterLifespan,
    GatewayAdapters,
    create_app,
)
from mh_gateway.config import ConfigSchema
from mh_gateway.config_manager import ConfigError, ConfigManager
from mh_gateway.context import (
    clear_current_user_id,
    ensure_trace_id,
    get_current_auth_token,
    get_current_cookies,
    get_current_locale,
    get_current_request,
    get_current_trace_id,
    get_current_user_id,
    reset_current_request,
    reset_current_trace_id,
    set_current_request,
    set_current_trace_id,
    set_current_user_id,
)
from mh_gateway.llm import (
    DefaultLLMProviderService,
    LLMConfigBackend,
    LLMHeaderResolver,
    LLMProviderConfig,
)
from mh_gateway.session import Session, SessionSummary, SimpleSession

__all__ = [
    "AdapterLifespan",
    "AuthorizationProvider",
    "ConfigError",
    "ConfigManager",
    "ConfigProvider",
    "ConfigSchema",
    "DefaultLLMProviderService",
    "EvalResultRepository",
    "GatewayAdapters",
    "LLMConfigBackend",
    "LLMHeaderResolver",
    "LLMProviderConfig",
    "LLMProviderService",
    "LLMResolveSpec",
    "M2MAuthenticator",
    "MetadataRepository",
    "OutboundAuthProvider",
    "OutboundRequestContext",
    "Session",
    "SessionRepository",
    "SessionSummary",
    "SimpleSession",
    "UserAuthenticator",
    "UserIdentity",
    "clear_current_user_id",
    "create_app",
    "ensure_trace_id",
    "get_current_auth_token",
    "get_current_cookies",
    "get_current_locale",
    "get_current_request",
    "get_current_trace_id",
    "get_current_user_id",
    "has_broad_permission",
    "match_permission",
    "reset_current_request",
    "reset_current_trace_id",
    "set_current_request",
    "set_current_trace_id",
    "set_current_user_id",
]
